[build]
  command = "npm run build"
  publish = "dist/portfolio/browser"

[[plugins]]
  package = "@netlify/plugin-replace"

[[plugins.inputs]]
  for = "src/environments/environment.prod.ts"
  from = "apiBase: ''"
  to = "apiBase: '${API_BASE_URL}'"
